/**
 * Executive Quality Report Generator
 *
 * Combines Health Score and Audit results into a professional report
 * (Markdown or HTML) for clients or agency stakeholders.
 *
 * Usage:
 *   tagops report [--output report.md]
 *   tagops report --format html [--output report.html]
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import chalk from "chalk";
import { listTags, listTriggers, listVariables, verifyGtmConnection } from "../lib/gtm-cli.js";
import { calculateHealthScore } from "./health-score.js";
import { auditWorkspace } from "./audit.js";
import type { ContainerHealthReport } from "./health-score.js";
import type { AuditReport, AuditIssue } from "../types/gtm.js";

export type ReportFormat = "md" | "html";

export interface ReportResult {
  outputPath: string;
  format: ReportFormat;
  score: number;
  grade: string;
  issueCount: number;
}

export interface ReportOptions {
  outputPath?: string;
  format?: ReportFormat;
}

/**
 * Generate a professional Markdown report.
 */
export function generateMarkdownReport(health: ContainerHealthReport, audit: AuditReport): string {
  const now = new Date().toLocaleString();
  const lines: string[] = [];
  const ln = (s = "") => lines.push(s);

  ln(`# GTM Workspace Quality Report`);
  ln(`> Generated on ${now} by TagOps CLI`);
  ln();

  // ── Executive Summary ──
  ln(`## Executive Summary`);
  ln();
  ln(`| Metric | Value |`);
  ln(`|--------|-------|`);
  ln(`| **Overall Health Grade** | **${health.grade}** (${health.overallScore}/100) |`);
  ln(`| Total Tags | ${health.totalTags} |`);
  ln(`| Total Triggers | ${health.totalTriggers} |`);
  ln(`| Total Variables | ${health.totalVariables} |`);
  ln(
    `| Critical Issues | ${audit.issues.filter((i) => i.type.includes("CONSENT") || i.type === "NO_TRIGGERS" || i.type === "MISSING_VARIABLE_REF" || i.type === "MISSING_SETUP_TAG").length} |`,
  );
  ln();
  ln("---");

  // ── Health Score Breakdown ──
  ln(`## Health Score Breakdown`);
  ln(`The container is scored across several key categories using weighted metrics.`);
  ln();
  ln(`| Category | Score | Weight | Status |`);
  ln(`|----------|-------|--------|--------|`);
  for (const c of health.components) {
    const status = c.score >= 90 ? "✅ Healthy" : c.score >= 70 ? "🟡 Warning" : "🔴 Critical";
    ln(`| ${c.name} | ${c.score}% | ${(c.weight * 100).toFixed(0)}% | ${status} |`);
    ln(`| | *Detail:* | *${c.details}* | |`);
  }
  ln();
  ln("---");

  // ── Audit Findings ──
  ln(`## Audit Findings`);
  ln(`Detailed scan of the workspace revealed the following specific configuration issues.`);
  ln();

  const grouped = new Map<string, AuditIssue[]>();
  for (const issue of audit.issues) {
    const list = grouped.get(issue.type) ?? [];
    list.push(issue);
    grouped.set(issue.type, list);
  }

  if (audit.issues.length === 0) {
    ln(`✅ **No issues found.** The workspace is following all best practices.`);
  } else {
    for (const [type, issues] of grouped.entries()) {
      ln(`### ${type.replace(/_/g, " ")}`);
      for (const i of issues) {
        const idPart = i.tagId
          ? ` (\`tag:${i.tagId}\`)`
          : i.triggerId
            ? ` (\`trigger:${i.triggerId}\`)`
            : i.variableId
              ? ` (\`var:${i.variableId}\`)`
              : "";
        ln(`- **${i.name}**${idPart}: ${i.detail}`);
      }
      ln();
    }
  }

  ln();
  ln("---");
  ln(`*Generated by TagOps — The professional GTM automation toolkit.*`);

  return lines.join("\n");
}

const HTML_ESCAPE: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/g, (ch) => HTML_ESCAPE[ch] ?? ch);
}

function gradeColor(grade: string): string {
  if (grade.startsWith("A")) return "#16a34a";
  if (grade.startsWith("B")) return "#65a30d";
  if (grade.startsWith("C")) return "#ca8a04";
  if (grade.startsWith("D")) return "#ea580c";
  return "#dc2626";
}

/**
 * Generate a self-contained styled HTML report (no external assets).
 */
export function generateHtmlReport(health: ContainerHealthReport, audit: AuditReport): string {
  const now = new Date().toLocaleString();
  const criticalCount = audit.issues.filter(
    (i) =>
      i.type.includes("CONSENT") ||
      i.type === "NO_TRIGGERS" ||
      i.type === "MISSING_VARIABLE_REF" ||
      i.type === "MISSING_SETUP_TAG",
  ).length;

  const componentRows = health.components
    .map((c) => {
      const status =
        c.score >= 90
          ? '<span class="pill pill-ok">Healthy</span>'
          : c.score >= 70
            ? '<span class="pill pill-warn">Warning</span>'
            : '<span class="pill pill-crit">Critical</span>';
      return `<tr><td>${escapeHtml(c.name)}</td><td class="num">${c.score}%</td><td class="num">${(c.weight * 100).toFixed(0)}%</td><td>${status}</td></tr><tr class="detail"><td colspan="4"><em>${escapeHtml(c.details)}</em></td></tr>`;
    })
    .join("");

  const grouped = new Map<string, AuditIssue[]>();
  for (const issue of audit.issues) {
    const list = grouped.get(issue.type) ?? [];
    list.push(issue);
    grouped.set(issue.type, list);
  }

  const issueSections =
    audit.issues.length === 0
      ? '<p class="ok">✅ No issues found. The workspace follows all best practices.</p>'
      : Array.from(grouped.entries())
          .map(([type, issues]) => {
            const items = issues
              .map((i) => {
                const idPart = i.tagId
                  ? ` <code>tag:${escapeHtml(i.tagId)}</code>`
                  : i.triggerId
                    ? ` <code>trigger:${escapeHtml(i.triggerId)}</code>`
                    : i.variableId
                      ? ` <code>var:${escapeHtml(i.variableId)}</code>`
                      : "";
                return `<li><strong>${escapeHtml(i.name)}</strong>${idPart}: ${escapeHtml(i.detail)}</li>`;
              })
              .join("");
            return `<h3>${escapeHtml(type.replace(/_/g, " "))}</h3><ul>${items}</ul>`;
          })
          .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>GTM Quality Report — ${escapeHtml(health.grade)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif; max-width: 920px; margin: 40px auto; padding: 0 24px; color: #0f172a; background: #f8fafc; }
  header { border-bottom: 1px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 28px; }
  h1 { margin: 0 0 6px; font-size: 28px; }
  h2 { font-size: 20px; margin-top: 36px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
  h3 { font-size: 16px; margin-top: 22px; }
  .meta { color: #64748b; font-size: 13px; }
  .grade { display: inline-block; font-size: 56px; font-weight: 700; padding: 8px 24px; border-radius: 12px; background: ${gradeColor(health.grade)}; color: #fff; }
  .score { font-size: 20px; color: #475569; margin-left: 12px; }
  .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 24px 0; }
  .card { background: #fff; border: 1px solid #e2e8f0; border-radius: 10px; padding: 14px 16px; }
  .card .label { color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
  .card .value { font-size: 24px; font-weight: 600; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
  th { background: #f1f5f9; font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; color: #475569; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  tr.detail td { color: #64748b; font-size: 13px; padding-top: 0; padding-bottom: 10px; border-bottom: 1px solid #e2e8f0; }
  .pill { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px; font-weight: 600; }
  .pill-ok { background: #dcfce7; color: #166534; }
  .pill-warn { background: #fef3c7; color: #92400e; }
  .pill-crit { background: #fee2e2; color: #991b1b; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; }
  code { background: #f1f5f9; padding: 1px 6px; border-radius: 4px; font-size: 12px; }
  .ok { color: #166534; background: #dcfce7; padding: 14px 16px; border-radius: 8px; }
  footer { color: #94a3b8; font-size: 12px; margin-top: 40px; text-align: center; }
</style>
</head>
<body>
<header>
  <h1>GTM Workspace Quality Report</h1>
  <div class="meta">Generated on ${escapeHtml(now)} by TagOps CLI</div>
  <div style="margin-top:22px;">
    <span class="grade">${escapeHtml(health.grade)}</span><span class="score">${health.overallScore}/100</span>
  </div>
</header>

<section class="summary">
  <div class="card"><div class="label">Tags</div><div class="value">${health.totalTags}</div></div>
  <div class="card"><div class="label">Triggers</div><div class="value">${health.totalTriggers}</div></div>
  <div class="card"><div class="label">Variables</div><div class="value">${health.totalVariables}</div></div>
  <div class="card"><div class="label">Critical Issues</div><div class="value">${criticalCount}</div></div>
</section>

<h2>Health Score Breakdown</h2>
<p class="meta">The container is scored across several key categories using weighted metrics.</p>
<table>
  <thead><tr><th>Category</th><th class="num">Score</th><th class="num">Weight</th><th>Status</th></tr></thead>
  <tbody>${componentRows}</tbody>
</table>

<h2>Audit Findings</h2>
${issueSections}

<footer>Generated by TagOps — the professional GTM automation toolkit.</footer>
</body>
</html>
`;
}

/**
 * Run the full report generation process.
 */
export async function runReport(options: ReportOptions = {}): Promise<ReportResult> {
  const format: ReportFormat = options.format ?? "md";

  // Fetch everything
  const [tags, triggers, variables] = await Promise.all([
    listTags(),
    listTriggers(),
    listVariables(),
  ]);

  if (tags.length === 0 && triggers.length === 0 && variables.length === 0) {
    await verifyGtmConnection();
  }

  // Calculate results
  const health = calculateHealthScore(tags, triggers, variables);
  const audit = await auditWorkspace({ tags, triggers, variables });

  // Generate content
  const content =
    format === "html" ? generateHtmlReport(health, audit) : generateMarkdownReport(health, audit);

  // Write to file
  const ext = format === "html" ? "html" : "md";
  const filename =
    options.outputPath ?? `gtm-quality-report-${new Date().toISOString().split("T")[0]}.${ext}`;
  const absolutePath = resolve(filename);
  writeFileSync(absolutePath, content);

  return {
    outputPath: absolutePath,
    format,
    score: health.overallScore,
    grade: health.grade,
    issueCount: audit.issues.length,
  };
}

export function printReportResult(result: ReportResult): void {
  console.log(chalk.bold("\n=== GTM Quality Report Generated ===\n"));
  console.log(`  📄 Path:   ${chalk.cyan(result.outputPath)}`);
  console.log(`  📝 Format: ${result.format.toUpperCase()}`);
  console.log(`  🏆 Grade:  ${chalk.green(result.grade)} (${result.score}/100)`);
  console.log(`  🔍 Issues: ${result.issueCount}\n`);
  console.log(
    chalk.gray(`  Share this file with your client or attach it to your deployment PR.\n`),
  );
}
