/**
 * Executive Quality Report Generator
 *
 * Combines Health Score and Audit results into a professional Markdown report
 * for clients or agency stakeholders.
 *
 * Usage:
 *   tagops report [--output report.md]
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import chalk from "chalk";
import { listTags, listTriggers, listVariables } from "../lib/gtm-cli.js";
import { calculateHealthScore } from "./health-score.js";
import { auditWorkspace } from "./audit.js";
import type { ContainerHealthReport } from "./health-score.js";
import type { AuditReport, AuditIssue } from "../types/gtm.js";

export interface ReportResult {
  outputPath: string;
  score: number;
  grade: string;
  issueCount: number;
}

/**
 * Generate a professional Markdown report.
 */
export function generateMarkdownReport(health: ContainerHealthReport, audit: AuditReport): string {
  const now = new Date().toLocaleString();
  const lines: string[] = [];
  const ln = (s = "") => lines.push(s);

  ln(`# GTM Workspace Quality Report`);
  ln(`> Generated on ${now} by TagOps CLI`);
  ln();

  // ── Executive Summary ──
  ln(`## Executive Summary`);
  ln();
  ln(`| Metric | Value |`);
  ln(`|--------|-------|`);
  ln(`| **Overall Health Grade** | **${health.grade}** (${health.overallScore}/100) |`);
  ln(`| Total Tags | ${health.totalTags} |`);
  ln(`| Total Triggers | ${health.totalTriggers} |`);
  ln(`| Total Variables | ${health.totalVariables} |`);
  ln(
    `| Critical Issues | ${audit.issues.filter((i) => i.type.includes("CONSENT") || i.type === "NO_TRIGGERS" || i.type === "MISSING_VARIABLE_REF").length} |`,
  );
  ln();
  ln("---");

  // ── Health Score Breakdown ──
  ln(`## Health Score Breakdown`);
  ln(`The container is scored across several key categories using weighted metrics.`);
  ln();
  ln(`| Category | Score | Weight | Status |`);
  ln(`|----------|-------|--------|--------|`);
  for (const c of health.components) {
    const status = c.score >= 90 ? "✅ Healthy" : c.score >= 70 ? "🟡 Warning" : "🔴 Critical";
    ln(`| ${c.name} | ${c.score}% | ${(c.weight * 100).toFixed(0)}% | ${status} |`);
    ln(`| | *Detail:* | *${c.details}* | |`);
  }
  ln();
  ln("---");

  // ── Audit Findings ──
  ln(`## Audit Findings`);
  ln(`Detailed scan of the workspace revealed the following specific configuration issues.`);
  ln();

  const grouped = new Map<string, AuditIssue[]>();
  for (const issue of audit.issues) {
    const list = grouped.get(issue.type) ?? [];
    list.push(issue);
    grouped.set(issue.type, list);
  }

  if (audit.issues.length === 0) {
    ln(`✅ **No issues found.** The workspace is following all best practices.`);
  } else {
    for (const [type, issues] of grouped.entries()) {
      ln(`### ${type.replace(/_/g, " ")}`);
      for (const i of issues) {
        const idPart = i.tagId
          ? ` (\`tag:${i.tagId}\`)`
          : i.triggerId
            ? ` (\`trigger:${i.triggerId}\`)`
            : i.variableId
              ? ` (\`var:${i.variableId}\`)`
              : "";
        ln(`- **${i.name}**${idPart}: ${i.detail}`);
      }
      ln();
    }
  }

  ln();
  ln("---");
  ln(`*Generated by TagOps — The professional GTM automation toolkit.*`);

  return lines.join("\n");
}

/**
 * Run the full report generation process.
 */
export async function runReport(outputPath?: string): Promise<ReportResult> {
  // Fetch everything
  const [tags, triggers, variables] = await Promise.all([
    listTags(),
    listTriggers(),
    listVariables(),
  ]);

  if (tags.length === 0 && triggers.length === 0) {
    throw new Error("Cannot connect to GTM or workspace is empty. Run 'tagops auth login' first.");
  }

  // Calculate results
  const health = calculateHealthScore(tags, triggers, variables);
  const audit = await auditWorkspace(); // This re-fetches internally, but that's okay for consistency or I could refactor audit to take tags/trig/vars

  // Generate Markdown
  const markdown = generateMarkdownReport(health, audit);

  // Write to file
  const filename = outputPath ?? `gtm-quality-report-${new Date().toISOString().split("T")[0]}.md`;
  const absolutePath = resolve(filename);
  writeFileSync(absolutePath, markdown);

  return {
    outputPath: absolutePath,
    score: health.overallScore,
    grade: health.grade,
    issueCount: audit.issues.length,
  };
}

export function printReportResult(result: ReportResult): void {
  console.log(chalk.bold("\n=== GTM Quality Report Generated ===\n"));
  console.log(`  📄 Path:  ${chalk.cyan(result.outputPath)}`);
  console.log(`  🏆 Grade: ${chalk.green(result.grade)} (${result.score}/100)`);
  console.log(`  🔍 Issues: ${result.issueCount}\n`);
  console.log(
    chalk.gray(`  Share this file with your client or attach it to your deployment PR.\n`),
  );
}
